apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 2
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: szalaigeri/test
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  selector:
    app: test
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30000
  type: LoadBalancer

